version: '3'

services:
  db:
    image: postgres:16.8
    restart: always
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pruebaud
    container_name: pruebaud
    volumes:
      - ./postgres:/var/lib/postgresql/data